name: docker_sanity
run-name: Checks docker containers sanity

on  : [push, pull_request] # Check if push needs branches prop
jobs:
    check-tests:
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v4

            - name: Create .env
              run : |
                echo $PWD
                echo "${{secrets.DUMMY_ENV_FILE}}" > .env
                ls
                  
            - name: Docker compose up
              run : docker compose up -d
                  
            - if  : ${{ failure() }}
              run : |
                echo Docker is not working properly
                docker compose down
                exit 1

            - name: Docker compose down
              if  : ${{ always() }}
              run : docker compose down