name: docker_sanity
run-name: Checks docker containers sanity

on  : [push, pull_request] # Check if push needs branches prop
jobs:
    check-tests:
        runs-on : ubuntu-latest
        steps   :
            - uses: actions/checkout@v4

            - name: Create .env
              run : |
                echo $PWD
                echo "${{secrets.DUMMY_ENV_FILE}}" > .env
                ls
                  
            - name: Docker sanity check
              run : |
                chmod +x ./.github/scripts/docker_sanity_check.sh
                ./.github/scripts/docker_sanity_check.sh
                  
            - if  : ${{ failure() }}
              run : |
                echo Docker is not working properly
                exit 1

            - run : echo Successfully checked docker sanity